export const GET_TODO_LOADING = 'GET_TODO_LOADING';
export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS';
export const GET_TODO_FAILED = 'GET_TODO_FAILED';

export const ADD_TODO_LOADING = 'ADD_TODO_LOADING';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILED = 'ADD_TODO_FAILED';

export const EDIT_TODO_LOADING = 'EDIT_TODO_LOADING';
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS';
export const EDIT_TODO_FAILED = 'EDIT_TODO_FAILED';

export const DELETE_TODO_LOADING = 'DELETE_TODO_LOADING';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILED = 'DELETE_TODO_FAILED';
